link_railstutorial: https://www.railstutorial.org/
link_railstutorial_help: https://www.railstutorial.org/help
link_railstutorial_book: https://www.railstutorial.org/book
link_railstutorial_contact: https://www.railstutorial.org/contact
link_screencasts_railstutorial: http://screencasts.railstutorial.org/
link_rubyonrails: http://rubyonrails.org/
link_newsrails: http://news.railstutorial.org/
link_michaelhartl: http://www.michaelhartl.com/
constant: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
num50: 50
num255: 255
num6: 6
